// 定义错误代码枚举
export enum ErrorCode {
    Success = 0,
    MissingParameters = -1,
    AdminUserIsExist = -2,
    UserIsNotExist = -3,
    PasswordError = -4,
    UserIsExist = -5,
    UserIsNotAdmin = -6,
    UserIsNotSuperAdmin = -7,
    ServerError = -8,
    UserIsFrozen = -9,
    TokenFailed = -10,
    InvalidUsername = -11,
    InvalidPassword = -12,
    ChatInsertError = -13,
    ChatQueryError = -14,
    ChatDeleteError = -15,
    ChatUpdateError = -16,
    SocketServerError = -17,
    SocketLoginError = -18,
    PictureReceivingFailure = -19,
    FileAppendError = -20,
    FileUploadError = -21,
    FileDeleteError = -22,
    FileQueryError = -23,
    FileUpdateError = -24,
    FileNotExist = -25,
    DatabaseError = -26,
    FileIsExist = -27,
    FileIsNotExist = -28,
    FileIsNotOwner = -29,
    FileIsNotPublic = -30,
    FamilyAlreadyExists = -31,
    FamilyIsNotExist = -32,
    FamilyIsNotOwner = -33,
    FamilyIsNotMember = -34,
    FamilyIsNotAdmin = -35,
    ApiAccessExeed = -36,
    ApiAccessError = -37,
    IllegalRequest = -38,
    NoFileUpload = -39,
    ErrorFileType = -40,
    FileOversize = -41,
    ConnectionError = -42,
    FriendOperationError = -43,
    GroupCreateError = -44,
    GroupNotFound = -45,
    GroupUpdateError = -46,
    GroupDissolveError = -47,
    GroupMessageError = -48,
    Unauthorized = -49,
    GroupDeleteError = -50,
    PersonalInfoIsExist = -51,
    UserIsApplying = -52,
    GroupAlreadyExists = -53,
}

// 创建错误代码和消息的映射
export const errorCodeMap = new Map<ErrorCode, string>([
    [ErrorCode.Success, "success"],
    [ErrorCode.MissingParameters, "缺少参数"],
    [ErrorCode.AdminUserIsExist, "账号名已存在"],
    [ErrorCode.UserIsNotExist, "用户不存在"],
    [ErrorCode.PasswordError, "密码错误"],
    [ErrorCode.UserIsExist, "用户已存在"],
    [ErrorCode.UserIsNotAdmin, "用户不是管理员"],
    [ErrorCode.UserIsNotSuperAdmin, "用户不是超级管理员"],
    [ErrorCode.ServerError, "服务器错误"],
    [ErrorCode.UserIsFrozen, "用户已被冻结"],
    [ErrorCode.TokenFailed, "token校验失败"],
    [ErrorCode.InvalidUsername, "用户名不合法"],
    [ErrorCode.InvalidPassword, "密码不合法"],
    [ErrorCode.ChatInsertError, "聊天信息插入失败"],
    [ErrorCode.ChatQueryError, "查询聊天记录错误"],
    [ErrorCode.ChatDeleteError, "删除聊天记录错误"],
    [ErrorCode.ChatUpdateError, "更新聊天记录错误"],
    [ErrorCode.SocketServerError, "socket服务器错误"],
    [ErrorCode.SocketLoginError, "socket登录失败"],
    [ErrorCode.PictureReceivingFailure, "图片接收失败"],
    [ErrorCode.FileAppendError, "文件追加失败"],
    [ErrorCode.FileUploadError, "文件上传失败"],
    [ErrorCode.FileDeleteError, "文件删除失败"],
    [ErrorCode.FileQueryError, "查询文件错误"],
    [ErrorCode.FileUpdateError, "更新文件信息错误"],
    [ErrorCode.FileNotExist, "文件不存在"],
    [ErrorCode.DatabaseError, "数据库错误"],
    [ErrorCode.FileIsExist, "文件已存在"],
    [ErrorCode.FileIsNotExist, "文件不存在"],
    [ErrorCode.FileIsNotOwner, "不是文件的拥有者"],
    [ErrorCode.FileIsNotPublic, "文件不是公开的"],
    [ErrorCode.FamilyAlreadyExists, "家庭已存在"],
    [ErrorCode.FamilyIsNotExist, "家庭不存在"],
    [ErrorCode.FamilyIsNotOwner, "不是家庭的拥有者"],
    [ErrorCode.FamilyIsNotMember, "不是家庭的成员"],
    [ErrorCode.FamilyIsNotAdmin, "不是家庭的超级管理员"],
    [ErrorCode.ApiAccessExeed, "API访问次数超过限制"],
    [ErrorCode.ApiAccessError, "API访问错误"],
    [ErrorCode.IllegalRequest, "非法请求"],
    [ErrorCode.NoFileUpload, "没有文件上传"],
    [ErrorCode.ErrorFileType, "文件类型错误"],
    [ErrorCode.FileOversize, "文件大小超过限制"],
    [ErrorCode.ConnectionError, "连接错误"],
    [ErrorCode.FriendOperationError, "好友操作错误"],
    [ErrorCode.GroupCreateError, "群组创建错误"],
    [ErrorCode.GroupNotFound, "群组不存在"],
    [ErrorCode.GroupUpdateError, "群组更新错误"],
    [ErrorCode.GroupDissolveError, "群组解散错误"],
    [ErrorCode.GroupMessageError, "群组消息错误"],
    [ErrorCode.Unauthorized, "没有权限"],
    [ErrorCode.GroupDeleteError, "群组删除错误"],
    [ErrorCode.PersonalInfoIsExist, "个人信息已存在"],
    [ErrorCode.UserIsApplying, "正在申请中"],
    [ErrorCode.GroupAlreadyExists, "群组已存在"],
]);

// 查找错误消息的函数
export function findErrorMessage(errorCode: ErrorCode): string {
    return errorCodeMap.get(errorCode) || "未知错误";
}

// 常用接口状态
export const CODE = {
    success: { code: ErrorCode.Success, message: errorCodeMap.get(ErrorCode.Success)!, key: "success" },
    missingParameters: { code: ErrorCode.MissingParameters, message: errorCodeMap.get(ErrorCode.MissingParameters)!, key: "missingParameters" },
    adminUserIsExist: { code: ErrorCode.AdminUserIsExist, message: errorCodeMap.get(ErrorCode.AdminUserIsExist)!, key: "adminUserIsExist" },
    userIsNotExist: { code: ErrorCode.UserIsNotExist, message: errorCodeMap.get(ErrorCode.UserIsNotExist)!, key: "userIsNotExist" },
    passwordError: { code: ErrorCode.PasswordError, message: errorCodeMap.get(ErrorCode.PasswordError)!, key: "passwordError" },
    userIsExist: { code: ErrorCode.UserIsExist, message: errorCodeMap.get(ErrorCode.UserIsExist)!, key: "userIsExist" },
    userIsNotAdmin: { code: ErrorCode.UserIsNotAdmin, message: errorCodeMap.get(ErrorCode.UserIsNotAdmin)!, key: "userIsNotAdmin" },
    userIsNotSuperAdmin: { code: ErrorCode.UserIsNotSuperAdmin, message: errorCodeMap.get(ErrorCode.UserIsNotSuperAdmin)!, key: "userIsNotSuperAdmin" },
    serverError: { code: ErrorCode.ServerError, message: errorCodeMap.get(ErrorCode.ServerError)!, key: "serverError" },
    userIsFrozen: { code: ErrorCode.UserIsFrozen, message: errorCodeMap.get(ErrorCode.UserIsFrozen)!, key: "userIsFrozen" },
    tokenFailed: { code: ErrorCode.TokenFailed, message: errorCodeMap.get(ErrorCode.TokenFailed)!, key: "tokenFailed" },
    invalidUsername: { code: ErrorCode.InvalidUsername, message: errorCodeMap.get(ErrorCode.InvalidUsername)!, key: "invalidUsername" },
    invalidPassword: { code: ErrorCode.InvalidPassword, message: errorCodeMap.get(ErrorCode.InvalidPassword)!, key: "invalidPassword" },
    chatInsertError: { code: ErrorCode.ChatInsertError, message: errorCodeMap.get(ErrorCode.ChatInsertError)!, key: "chatInsertError" },
    chatQueryError: { code: ErrorCode.ChatQueryError, message: errorCodeMap.get(ErrorCode.ChatQueryError)!, key: "chatQueryError" },
    chatDeleteError: { code: ErrorCode.ChatDeleteError, message: errorCodeMap.get(ErrorCode.ChatDeleteError)!, key: "chatDeleteError" },
    chatUpdateError: { code: ErrorCode.ChatUpdateError, message: errorCodeMap.get(ErrorCode.ChatUpdateError)!, key: "chatUpdateError" },
    socketServerError: { code: ErrorCode.SocketServerError, message: errorCodeMap.get(ErrorCode.SocketServerError)!, key: "socketServerError" },
    socketLoginError: { code: ErrorCode.SocketLoginError, message: errorCodeMap.get(ErrorCode.SocketLoginError)!, key: "socketLoginError" },
    pictureReceivingFailure: { code: ErrorCode.PictureReceivingFailure, message: errorCodeMap.get(ErrorCode.PictureReceivingFailure)!, key: "pictureReceivingFailure" },
    fileAppendError: { code: ErrorCode.FileAppendError, message: errorCodeMap.get(ErrorCode.FileAppendError)!, key: "fileAppendError" },
    fileUploadError: { code: ErrorCode.FileUploadError, message: errorCodeMap.get(ErrorCode.FileUploadError)!, key: "fileUploadError" },
    fileDeleteError: { code: ErrorCode.FileDeleteError, message: errorCodeMap.get(ErrorCode.FileDeleteError)!, key: "fileDeleteError" },
    fileQueryError: { code: ErrorCode.FileQueryError, message: errorCodeMap.get(ErrorCode.FileQueryError)!, key: "fileQueryError" },
    fileUpdateError: { code: ErrorCode.FileUpdateError, message: errorCodeMap.get(ErrorCode.FileUpdateError)!, key: "fileUpdateError" },
    fileNotExist: { code: ErrorCode.FileNotExist, message: errorCodeMap.get(ErrorCode.FileNotExist)!, key: "fileNotExist" },
    databaseError: { code: ErrorCode.DatabaseError, message: errorCodeMap.get(ErrorCode.DatabaseError)!, key: "databaseError" },
    fileIsExist: { code: ErrorCode.FileIsExist, message: errorCodeMap.get(ErrorCode.FileIsExist)!, key: "fileIsExist" },
    fileIsNotExist: { code: ErrorCode.FileIsNotExist, message: errorCodeMap.get(ErrorCode.FileIsNotExist)!, key: "fileIsNotExist" },
    fileIsNotOwner: { code: ErrorCode.FileIsNotOwner, message: errorCodeMap.get(ErrorCode.FileIsNotOwner)!, key: "fileIsNotOwner" },
    fileIsNotPublic: { code: ErrorCode.FileIsNotPublic, message: errorCodeMap.get(ErrorCode.FileIsNotPublic)!, key: "fileIsNotPublic" },
    familyAlreadyExists: { code: ErrorCode.FamilyAlreadyExists, message: errorCodeMap.get(ErrorCode.FamilyAlreadyExists)!, key: "familyAlreadyExists" },
    familyIsNotExist: { code: ErrorCode.FamilyIsNotExist, message: errorCodeMap.get(ErrorCode.FamilyIsNotExist)!, key: "familyIsNotExist" },
    familyIsNotOwner: { code: ErrorCode.FamilyIsNotOwner, message: errorCodeMap.get(ErrorCode.FamilyIsNotOwner)!, key: "familyIsNotOwner" },
    familyIsNotMember: { code: ErrorCode.FamilyIsNotMember, message: errorCodeMap.get(ErrorCode.FamilyIsNotMember)!, key: "familyIsNotMember" },
    familyIsNotAdmin: { code: ErrorCode.FamilyIsNotAdmin, message: errorCodeMap.get(ErrorCode.FamilyIsNotAdmin)!, key: "familyIsNotAdmin" },
    apiAccessExeed: { code: ErrorCode.ApiAccessExeed, message: errorCodeMap.get(ErrorCode.ApiAccessExeed)!, key: "apiAccessExeed" },
    apiAccessError: { code: ErrorCode.ApiAccessError, message: errorCodeMap.get(ErrorCode.ApiAccessError)!, key: "apiAccessError" },
    illegalRequest: { code: ErrorCode.IllegalRequest, message: errorCodeMap.get(ErrorCode.IllegalRequest)!, key: "illegalRequest" },
    noFileUpload: { code: ErrorCode.NoFileUpload, message: errorCodeMap.get(ErrorCode.NoFileUpload)!, key: "noFileUpload" },
    errorFileType: { code: ErrorCode.ErrorFileType, message: errorCodeMap.get(ErrorCode.ErrorFileType)!, key: "errorFileType" },
    fileOversize: { code: ErrorCode.FileOversize, message: errorCodeMap.get(ErrorCode.FileOversize)!, key: "fileOversize" },
    connectionError: { code: ErrorCode.ConnectionError, message: errorCodeMap.get(ErrorCode.ConnectionError)!, key: "connectionError" },
    friendOperationError: { code: ErrorCode.FriendOperationError, message: errorCodeMap.get(ErrorCode.FriendOperationError)!, key: "friendOperationError" },
    groupCreateError: { code: ErrorCode.GroupCreateError, message: errorCodeMap.get(ErrorCode.GroupCreateError)!, key: "groupCreateError" },
    groupNotFound: { code: ErrorCode.GroupNotFound, message: errorCodeMap.get(ErrorCode.GroupNotFound)!, key: "groupNotFound" },
    groupUpdateError: { code: ErrorCode.GroupUpdateError, message: errorCodeMap.get(ErrorCode.GroupUpdateError)!, key: "groupUpdateError" },
    groupDissolveError: { code: ErrorCode.GroupDissolveError, message: errorCodeMap.get(ErrorCode.GroupDissolveError)!, key: "groupDissolveError" },
    groupMessageError: { code: ErrorCode.GroupMessageError, message: errorCodeMap.get(ErrorCode.GroupMessageError)!, key: "groupMessageError" },
    unauthorized: { code: ErrorCode.Unauthorized, message: errorCodeMap.get(ErrorCode.Unauthorized)!, key: "unauthorized" },
    groupDeleteError: { code: ErrorCode.GroupDeleteError, message: errorCodeMap.get(ErrorCode.GroupDeleteError)!, key: "groupDeleteError" },
    personalInfoIsExist: { code: ErrorCode.PersonalInfoIsExist, message: errorCodeMap.get(ErrorCode.PersonalInfoIsExist)!, key: "personalInfoIsExist" },
    userIsApplying: { code: ErrorCode.UserIsApplying, message: errorCodeMap.get(ErrorCode.UserIsApplying)!, key: "userIsApplying" },
};